spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/wetracker
    user: postgres
    password: root
    out-of-order: true

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 8
    name: WetrackDevelopment
    password: root
    url: jdbc:postgresql://localhost:5432/wetracker
    username: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    ddl-auto: validate
    format_sql: true

server:
  port: 8080

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

