CREATE TABLE WE_TRACK_USERS
(
    ID                               BIGSERIAL,
    USER_ID                          TEXT,
    MOBILE_MODEL                     TEXT,
    IP_ADDRESS                       TEXT,
    COUNTRY                          TEXT,
    ONE_SIGNAL_EXTERNAL_USERID       TEXT,
    MOBILE_VERSION                   TEXT,
    Expiry_TIME                      TEXT,
    IS_USER_CREATED_IN_WETRACK_SERVICE BOOLEAN,
    IS_PURCHASED                      BOOLEAN,
    TOKEN_HEADER                      TEXT,
    SCHEMA_NAME                      TEXT,
    IS_NUMBER_ADDER                  BOOLEAN,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,USER_ID)
);


CREATE INDEX WE_TRACK_USERS_INDEX
    ON WE_TRACK_USERS (USER_ID, IS_NUMBER_ADDER,Expiry_TIME);




CREATE TABLE AUTH_TOKEN
(
    ID            BIGSERIAL,
    USER_ID       TEXT,
    AUTH_TOKEN     TEXT,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,USER_ID,AUTH_TOKEN)
);

CREATE INDEX AUTH_TOKEN_INDEX
    ON AUTH_TOKEN (USER_ID, AUTH_TOKEN);





CREATE TABLE PURCHASED_DETAILS
(
    ID                               BIGSERIAL,
    USER_ID                          TEXT,
    PURCHASE_MODE                    TEXT,
    PURCHASE_PLATFORM                TEXT,
    COUNTRY                          TEXT,
    AMOUNT                           TEXT,
    TRANSATION_ID                    TEXT,
    TRANSACTION_REMARK               TEXT,
    EXPIRY_DATE                      TEXT,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,USER_ID)
);


CREATE TABLE NUMBER_FOR_USERS
(
    ID                BIGSERIAL,
    USER_ID           TEXT,
    NUMBER            TEXT,
    TOKEN_HEADER      TEXT,
    COUNTRY_CODE      TEXT,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,USER_ID,TOKEN_HEADER)
);

CREATE INDEX NUMBER_FOR_USERS_INDEX
    ON NUMBER_FOR_USERS (USER_ID, NUMBER,TOKEN_HEADER,COUNTRY_CODE);



CREATE TABLE MODEL_COMBINATION
(
    ID                BIGSERIAL,
    MODEL_ID           TEXT,
    MODEL_NUMBER       TEXT,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,MODEL_ID)
);



CREATE INDEX MODEL_COMBINATION_INDEX
    ON MODEL_COMBINATION (MODEL_ID, MODEL_NUMBER);









