CREATE TABLE EVENT_TABLE
(
    ID                 BIGSERIAL,
    EVENT_NAME         TEXT,
    EVENT_NORMAL_IMAGE TEXT,
    EVENT_IMAGE        TEXT,
    EVENT_BODY         TEXT,
    EVENT_COUNTRY      TEXT,
    IMAGE_MORNING      TEXT,
    IMAGE_AFTERNOON    TEXT,
    IMAGE_EVENING      TEXT,
    IMAGE_NIGHT        TEXT,
    EVENT_ID           TEXT,
    CREATED_AT         TIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP NOT NULL,
    PRIMARY KEY (ID, EVENT_COUNTRY)
);

CREATE INDEX EVENT_TABLE_INDEX
    ON EVENT_TABLE (ID, EVENT_COUNTRY, EVENT_ID);


/*Event History Table*/
CREATE TABLE EVENT_HISTORY
(
    ID            BIGSERIAL,
    EVENT_ID      TEXT,
    USER_ID       TEXT,
    EVENT_COUNTRY TEXT
);
CREATE INDEX EVENT_HISTORY_INDEX
    ON EVENT_HISTORY (USER_ID, EVENT_COUNTRY, EVENT_ID);


/*Message Between User*/
CREATE TABLE MESSAGE_BETWEEN_USER
(
    ID                BIGSERIAL,
    MESSAGE           TEXT,
    MESSAGE_USER_ID   TEXT,
    MESSAGE_IMAGE_URL TEXT,
    ADMIN_ID          TEXT,
    IS_SEEN           BOOLEAN,
    MESSAGER_ID       TEXT,
    CREATED_AT        TIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX MESSAGE_BETWEEN_USER_INDEX
    ON MESSAGE_BETWEEN_USER (ID, MESSAGE_USER_ID, ADMIN_ID);



CREATE TABLE MESSAGE_BASED_APPLICATION
(
    ID                 BIGSERIAL,
    IS_FREE_MODE       BOOLEAN,
    APP_VERSION        TEXT,
    IS_FORCE_UPDATE    BOOLEAN,
    IS_APP_IN_LIVE     BOOLEAN,
    IS_RAZORPAY_ACTIVE BOOLEAN,
    CREATED_AT         TIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX MESSAGE_BASED_APPLICATION_INDEX
    ON MESSAGE_BASED_APPLICATION (ID);

CREATE TABLE AUDIT_MASTER
(
    ID           BIGSERIAL PRIMARY KEY,
    USER_ID      TEXT      NOT NULL,
    MODULES      TEXT      NOT NULL,
    IP_ADDRESS   TEXT,
    TASK         TEXT,
    TODAY        TEXT,
    PACKAGE_NAME TEXT,
    CREATED_AT   TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP NOT NULL
);

CREATE INDEX AUDIT_MASTER_INDEX
    ON AUDIT_MASTER (ID, USER_ID, PACKAGE_NAME);



alter table UPI_DETAILS
    add column button_color TEXT;
alter table UPI_DETAILS
    add column button_bg TEXT;
alter table UPI_DETAILS
    add column offer_price TEXT;
alter table UPI_DETAILS
    add column offer_percentage TEXT;



CREATE TABLE MESSAGED_USER
(
    ID              BIGSERIAL,
    MESSAGE_USER_ID TEXT,
    CREATED_AT      TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP NOT NULL,
    PRIMARY KEY (ID, MESSAGE_USER_ID)
);
CREATE INDEX MESSAGED_USER_INDEX
    ON MESSAGED_USER (ID, MESSAGE_USER_ID);
